### ISSUE TITLE
Escape name of zip files

### ISSUE THREAD

**Issue by mosconidebugging** [admiral0/MinecraftSolder#5]
Zip files downloaded by Technic Launcher are saved in a temporary directory on the file system
(`.techinc/modpacks/xxx/cache/modname`). On Windows there are some reserved characters that cannot be used to create files.
For example, on Windows, a mod named `bad|mod` makes impossible to install the entire modpack because `|` is not allowed.

**Comment by admiral0** [comment]
In Progress.

**Comment by admiral0** [comment]
Fixed with 0.4.5
